// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwcFzi0h5Sf4MZuSmpET5ybgIYpEBRIx8',
    appId: '1:698278768669:web:dbc11413082c17f07616f4',
    messagingSenderId: '698278768669',
    projectId: 'portfolio-54852',
    authDomain: 'portfolio-54852.firebaseapp.com',
    storageBucket: 'portfolio-54852.firebasestorage.app',
    measurementId: 'G-VVTT1RSWYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7-wZV2n7wp2h0-fcG8cDafmnYgvtnq0',
    appId: '1:698278768669:android:26cc675f43e3c4d17616f4',
    messagingSenderId: '698278768669',
    projectId: 'portfolio-54852',
    storageBucket: 'portfolio-54852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBzS-nJj3Ab8UewFa_vMg5aTdzHvdzt0',
    appId: '1:698278768669:ios:6c116bde072d1b497616f4',
    messagingSenderId: '698278768669',
    projectId: 'portfolio-54852',
    storageBucket: 'portfolio-54852.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBzS-nJj3Ab8UewFa_vMg5aTdzHvdzt0',
    appId: '1:698278768669:ios:6c116bde072d1b497616f4',
    messagingSenderId: '698278768669',
    projectId: 'portfolio-54852',
    storageBucket: 'portfolio-54852.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwcFzi0h5Sf4MZuSmpET5ybgIYpEBRIx8',
    appId: '1:698278768669:web:dbc11413082c17f07616f4',
    messagingSenderId: '698278768669',
    projectId: 'portfolio-54852',
    authDomain: 'portfolio-54852.firebaseapp.com',
    storageBucket: 'portfolio-54852.firebasestorage.app',
    measurementId: 'G-VVTT1RSWYM',
  );

}